### ISSUE TITLE
Revised Board?

### ISSUE THREAD

**Issue by shbhm-0711** [MitchBradley/Esp32PrinterController#2]
I did not knew how to contact you for the revised edition, have you uploaded it already? if not, can you please do it. It'll be a great help.

**Comment by MitchBradley** [comment]
I have abandoned work on this design in favor of Bart Dring's 6-pack design.  https://github.com/bdring/6-Pack_CNC_Controller

**Comment by MitchBradley** [comment]
There is one major design flaw in the Esp32PrinterController.  The fan driving based on ULN2803 with outputs connected in parallel does not work as intended.  I copied that part of the circuit from the felixstorm design without checking it carefully.  The intention of paralleling the outputs was to provide more current than a single output can sink.  The problem is that ULN2803 has bipolar transistors, and bipolar transistors will not share current when they are connected in parallel (FETs will share, bipolars will not). With bipolars in parallel, the transistor with the lowest resistance will take the most current, heat up, and then take even more of the current, until it fails.  Then the next lowest resistance will do the same, until they all fail.  It happens very quickly.  The only safe way to use a ULN2803 is to use each channel to drive a separate load that is within the channel's current rating.

On my prototype boards, after one of the ULN2803s failed and I realized why, I removed the ULN2803s and replaced them with 3 logic-gate MOSFETs.

**Comment by shbhm-0711** [comment]
Thank you for replying, I see the issue and I've read it before in your edits, it is really helpful of you to provide me with the work around for the issue. I'll work around that, But it'll be really helpful if I can also get the Configuration files used in the prototype for the Marlin Firmware as I want to test things and then assemble it into a printer and I don't want to use grbl because it's made for CNC only as far as I know. Best Regards.

**Comment by MitchBradley** [comment]
What I have is in this branch https://github.com/MitchBradley/Marlin/tree/ESP32_Anycubic_i3  .  I haven't touched it in over a year so it is bound to be behind the Marlin curve.

**Comment by MitchBradley** [comment]
I pushed my latest schematics to a new branch https://github.com/MitchBradley/Esp32PrinterController/tree/rev2 .  The pdfs and gerbers have not been updated, only the KiCad files.

**Comment by shbhm-0711** [comment]
Ok, that would be great help. Thank you again for providing your guidance.
